# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d09308f8bb6d2a63828098111e823a040ebf984440be61b8defcdfbc56a6b84d070e77b19fb5ded5c9b659d5cf76e101cad404a91eaba69103687dd3c72040

test:
  secret_key_base: 9c91b3246847d6c62185cf28e24428648d9c4c460ef2a3cb99ab953a8e8c1ea825dba8836a6c2ce5847d05a3e8326a5315387f683094b2e8a4439307681af1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
